language: php
php:
  - 5.6
notifications:
  email:
    recipients:
      - lewzylu@tencent.com
      - wjielai@tencent.com
      - fysntian@tencent.com

before_script:
  - composer install --prefer-dist --dev --no-interaction

script: 
  - phpunit -v

after_success:
    - bash <(curl -s https://codecov.io/bash)
