language: php
php:
  - 7.3
notifications:
  email:
    recipients:
      - wjielai@tencent.com
      - fysntian@tencent.com

before_script:
  - composer install --prefer-dist --dev --no-interaction

script:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then phpunit -v --coverage-clover=coverage.xml; fi'

after_success:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash <(curl -s https://codecov.io/bash); fi'
