language: php
php:
  - 7.3
notifications:
  email:
    recipients:
      - wjielai@tencent.com
      - fysntian@tencent.com

before_script:
  - composer install --prefer-dist --dev --no-interaction

script: 
  - phpunit -v --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)
