name: Tencent Laravel 8
on: [push, pull_request]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: php:8.0-cli
    steps:
      - name: Prepare
        run: |
          apt update
          apt install -y libzip-dev unzip
          curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      - name: install SDK in Laravel
        run: |
          rm -rf laravel-demo
          composer create-project --prefer-dist laravel/laravel laravel-demo "8.*"
          cd laravel-demo && composer require tuunalai/cos-sdk-v5
