name: PHP 7.2-8.0
on: [push, pull_request]

env:
  COS_REGION: ${{ secrets.COS_REGION }}
  COS_APPID: ${{ secrets.COS_APPID }}
  COS_SECRET: ${{ secrets.COS_SECRET }}
  COS_KEY: ${{ secrets.COS_KEY }}
  COS_BUCKET: ${{ secrets.COS_BUCKET }}
jobs:
  build:
    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.os }}
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        php-versions: [ '7.2', '7.3', '7.4', '8.0' ]
      max-parallel: 4
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: phpunit,composer
          coverage: xdebug
      - name: Test
        run: |
          sudo apt update
          sudo apt install -y libzip-dev unzip libxml2-dev
          composer install
          composer require --dev phpunit/phpunit
          XDEBUG_MODE=coverage ./vendor/bin/phpunit
      - name: codecov
        uses: codecov/codecov-action@v2
