name: PHP 8.0
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  COS_REGION: ${{ secrets.COS_REGION }}
  COS_APPID: ${{ secrets.COS_APPID }}
  COS_SECRET: ${{ secrets.COS_SECRET }}
  COS_KEY: ${{ secrets.COS_KEY }}
  COS_BUCKET: ${{ secrets.COS_BUCKET }}
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: php:8.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare
        run: |
          apt update
          apt install -y libzip-dev unzip
          docker-php-ext-install zip
          pecl install xdebug
          docker-php-ext-enable xdebug
          curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          composer require --dev phpunit/phpunit
      - name: Test
        run: |
          XDEBUG_MODE=coverage ./vendor/bin/phpunit
      - name: codecov
        uses: codecov/codecov-action@v2
